# Generated by Django 3.0.8 on 2020-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200808_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(default='No return No exchange', max_length=200),
        ),
    ]
